export const textDefault = '#555'
export const textLight = '#aaa'
export const primary = '#6fcea1'
export const secondary = '#3498db'
export const primaryBackground = '#f6f7f6'
export const secondaryBackground = '#fff'
export const overlayBackground = '#000'
export const danger = '#c0392b'
