projects:
  teulu:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: maiowbtj45fljfcrxshrnwwavy
        maxDepth: 5
      endpoints:
        prod: >-
          https://hp5bwxviq5cq3l7alz6kgkbg2a.appsync-api.eu-west-1.amazonaws.com/graphql
